mongodb:
  container_name: mongodb
  image: mongo
  ports:
    - "27017:27017"
api:
  container_name: nodejs
  build: ./api
  working_dir: /usr/src/api
  env_file:
    - ./api/.env
  links:
    - mongodb
  ports:
    - "3000:3000"
  command: node src/server
client:
  container_name: nginx
  build: ./client
  environment:
   - NGINX_HOST=localhost
   - NGINX_PORT=80
  working_dir: /usr/share/nginx/html
  ports:
    - "8080:80"
